name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -X
            -Dsonar.projectKey=your-project-key
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
